### ISSUE TITLE
 API keys with referer restrictions cannot be used with this API

### ISSUE THREAD

**Issue by gezimapi** [nchaulet/node-geocoder#303]
hi ,

Im getting this error 

Error: Status is REQUEST_DENIED. API keys with referer restrictions cannot be used with this API.
    at /var/www/store_api/node_modules/node-geocoder/lib/geocoder/googlegeocoder.js:89:25
    at IncomingMessage.<anonymous> (/var/www/store_api/node_modules/node-geocoder/lib/httpadapter/httpadapter.js:65:9)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Thx in advance

**Comment by nchaulet** [comment]
Looks your API key is not valid for geocoding, which geocoder are you using? and how you configured it?
